[tool.isort]
known_first_party = "nvflops"
profile = "black"
multi_line_output = 3
line_length = 120
skip = [".git", ".eggs", "venv", ".venv", "versioneer.py", "_version.py", "conf.py", "nvflops/__init__.py"]
skip_glob = [ "*.pyi" ]

[tool.black]
line-length = 120
target-version = ['py38']
include = '\.pyi?$'
exclude = '''
(
  /(
    # exclude a few common directories in the root of the project
      \.eggs
    | \.git
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | \.pytype
    | _build
    | buck-out
    | build
    | dist
  )/
  | _version.py
)
'''
